name: Merge Master into Main

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Merge master into main
        run: |
          git fetch origin
          git checkout main
          git pull origin main
          git merge origin/master --no-ff --commit -m "Automated merge of master into main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
