name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this to your default branch if it's not 'main'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}  # Reference the secret here
          publish_dir: ./build
          publish_branch: gh-pages
